function [scenario, egoVehicle] = createDrivingScenario()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 23.2 (R2023b) and Automated Driving Toolbox 23.2 (R2023b).
% Generated on: 26-Apr-2024 00:07:35

% Construct a drivingScenario object.
scenario = drivingScenario;

% Add all road segments
roadCenters = [43.4 4.5 0;
    7.3 3.4 0];
laneSpecification = lanespec(2);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road');

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [38 5.3 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car');
waypoints = [38 5.3 0;
    27 4.3 0;
    22.5 5.6 0];
speed = [30;40;30];
waittime = [0;0;0];
trajectory(egoVehicle, waypoints, speed, waittime);

% Add the non-ego actors
car1 = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [19.3 1.3 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car1');
waypoints = [19.3 1.3 0;
    26.4 2.1 0;
    31.7 1.1 0;
    36.3 1.8 0];
speed = [30;30;30;30];
trajectory(car1, waypoints, speed);

pedestrian = actor(scenario, ...
    'ClassID', 4, ...
    'Length', 0.24, ...
    'Width', 0.45, ...
    'Height', 1.7, ...
    'Position', [24.8 6.5 0], ...
    'RCSPattern', [-8 -8;-8 -8], ...
    'Mesh', driving.scenario.pedestrianMesh, ...
    'Name', 'Pedestrian');
waypoints = [24.8 6.5 0;
    24.2 4.3 0;
    25.2 1.6 0];
speed = [5;3;4];
waittime = [0;0;0];
trajectory(pedestrian, waypoints, speed, waittime);

