function [scenario, egoVehicle] = safe2()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 23.2 (R2023b) and Automated Driving Toolbox 23.2 (R2023b).
% Generated on: 25-Apr-2024 23:16:30

% Construct a drivingScenario object.
scenario = drivingScenario;

% Add all road segments
roadCenters = [43.2 2.7 0;
    25.4 -2.9 0;
    6.8 2.4 0];
laneSpecification = lanespec(2);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road');

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [37.4 2.1 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car');
waypoints = [37.4 2.1 0;
    27.4 -1.1 0;
    15.5 -0.1 0;
    11.2 2.2 0];
speed = [30;30;30;30];
trajectory(egoVehicle, waypoints, speed);

% Add the non-ego actors
car1 = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [14.7 -3.3 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car1');
waypoints = [14.7 -3.3 0;
    24.8 -4.3 0;
    30.4 -4.7 0;
    36.1 -2.5 0];
speed = [30;30;30;30];
trajectory(car1, waypoints, speed);

pedestrian = actor(scenario, ...
    'ClassID', 4, ...
    'Length', 0.24, ...
    'Width', 0.45, ...
    'Height', 1.7, ...
    'Position', [26.4 -5.9 0], ...
    'RCSPattern', [-8 -8;-8 -8], ...
    'Mesh', driving.scenario.pedestrianMesh, ...
    'Name', 'Pedestrian');
waypoints = [26.4 -5.9 0;
    22 -5.5 0];
speed = [1.5;1.5];
trajectory(pedestrian, waypoints, speed);

